spring:
  profiles:
    active: local
    group:
      localall:
        - "local"
        - "swagger"
        - "runners"
        - "prometheus"
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: local
  redis:
    port: 6379
    host: localhost

  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: postgres
    password: admin
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        #        generate_statistics: true
        jdbc:
          batch_size: 100
        order_inserts: true

---
spring:
  config:
    activate:
      on-profile: prometheus

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: samples-inmem-redis-postgres